package Model.Users;

public enum Permission {
    CREATE_BILL,
    VIEW_BILL,
    MANAGE_INVENTORY,
    VIEW_INVENTORY,
    VIEW_ALL_SECTORS,
    MANAGE_SECTORS,
    CREATE_SECTOR,
    CREATE_CATEGORY,
    DELETE_CATEGORY
}
